name: CI
on:
  push:
    branches:
      - main
  pull_request:

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          # Note: By default, the checkout action will only clone the latest commit of the branch, which will cause issues as Nx needs to compute the difference between the base and head. Using the fetch-depth: 0 parameter will clone the entire repository, which is not optimal but functional.
          fetch-depth: 0

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          
      - run: yarn install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v3
        # This line is needed for nx affected to work when CI is running on a PR
      - run: yarn exitzero git branch --track main origin/main

      - name: Extract keys
        run: yarn lingui:extract
      
      - run: |
          if ! npx nx affected -t lint --fix; then
            echo "::error:: Lint failed, check actions tab for more info"
          fi

      - run: |
          git add apps/postybirb-ui/src/**/*.po lang/
          git commit -m 'chore: extract lang messages'

          git add ./
          git commit -m 'lint: prettier and eslint fix'

          git push