name: i18n extract keys
on:
  pull_request:
    types:
      - opened
    branches:
      - 'i18n/**'
    paths:
      - 'apps/postybirb-ui/src/**.ts'
      - 'apps/postybirb-ui/src/**.tsx'

jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Extract keys
        run: yarn lingui:extract